### ISSUE TITLE
jpype.dbapi2: getParameterMetaData not implemented

### ISSUE THREAD

**Issue by slokhorst** [jpype-project/jpype#1027]
When trying to execute an SQL statement with `jpype.dbapi2` on my [Filemaker JDBC](https://support.claris.com/s/article/Software-Update-FileMaker-xDBC-client-drivers-for-FileMaker-1503692806454?language=en_US) database:

```
Traceback (most recent call last):
  File "com.filemaker.jdbc3.CommonJ3Statement.java", line -1, in com.filemaker.jdbc3.CommonJ3Statement.getParameterMetaData
  File "com.filemaker.jdbc.Driver.java", line -1, in com.filemaker.jdbc.Driver.notImplemented
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    cursor.execute("SELECT * FROM Test")
  File "/home/sebas/.local/lib/python3.10/site-packages/jpype/dbapi2.py", line 1054, in execute
    self._executeone(parameters)
  File "/home/sebas/.local/lib/python3.10/site-packages/jpype/dbapi2.py", line 1058, in _executeone
    self._setParams(params)
  File "/home/sebas/.local/lib/python3.10/site-packages/jpype/dbapi2.py", line 698, in _setParams
    meta = self._statement.getParameterMetaData()
com.filemaker.jdbc.com.filemaker.jdbc.FMSQLException: com.filemaker.jdbc.FMSQLException: [FileMaker][FileMaker JDBC] This method is not yet implemented.
```

So apparently, the Filemaker JDBC does not implement the `getParameterMetaData` function. Is this function absolutely necessary to use `jpype.dbapi2`? Or is the Filemaker implementation just incomplete/broken? I noticed that it works fine together with jaydebeapi or DBeaver.. those probably don't use this JDBC function?

**Comment by Thrameos** [comment]
I don't see any documentation that indicates that getParameterMetaData is optional.  JPype dbapi2 uses this call to determine the type of marshaller to use.   Those other packages use `getObject`  exclusively so they don't have much marshalling.  If you show me the code I can see if there is a good way to bypass the marshalling function.  I believe if the marshallers are specified then it doesn't ask for meta data, but I will need to verify that.
