### ISSUE TITLE
Fail to install because of setuptool change

### ISSUE THREAD

**Issue by PrimWILL** [jpype-project/jpype#1205]
After [removal of test command in setuptool with version 72.0.0](https://github.com/pypa/setuptools/issues/4519), fail to install JPype.

- Python version: 3.9
- OS: Sonoma 14.5 (Silicon chip)
```
pip install JPype1
Collecting JPype1
  Using cached JPype1-1.5.0.tar.gz (819 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/test1/.pyenv/versions/3.9.17/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/test1/.pyenv/versions/3.9.17/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/test1/.pyenv/versions/3.9.17/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/bl/31307nzn5kn25tz85p5q5hy80000gn/T/pip-build-env-lw0iwva1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/bl/31307nzn5kn25tz85p5q5hy80000gn/T/pip-build-env-lw0iwva1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/bl/31307nzn5kn25tz85p5q5hy80000gn/T/pip-build-env-lw0iwva1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/bl/31307nzn5kn25tz85p5q5hy80000gn/T/pip-build-env-lw0iwva1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 26, in <module>
        File "/private/var/folders/bl/31307nzn5kn25tz85p5q5hy80000gn/T/pip-install-5qfv_k8g/jpype1_d8c4b65331a546b59b6ab924b8519df4/setupext/__init__.py", line 25, in <module>
          from . import pytester
        File "/private/var/folders/bl/31307nzn5kn25tz85p5q5hy80000gn/T/pip-install-5qfv_k8g/jpype1_d8c4b65331a546b59b6ab924b8519df4/setupext/pytester.py", line 20, in <module>
          from setuptools.command.test import test as TestCommand
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

- Python version: 3.9
- OS: Amazon linux 2023 (arm64)

```
Collecting JPype1>=0.7.0 (from konlpy==0.5.2->-r /home/ec2-user/temp/requirements.txt (line 26))
Downloading JPype1-1.5.0.tar.gz (819 kB)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.1/819.1 kB 14.4 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [21 lines of output]
    Traceback (most recent call last):
      File "/home/ec2-user/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
        main()
      File "/home/ec2-user/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/ec2-user/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
      File "/tmp/pip-build-env-6t_et_ky/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=[])
      File "/tmp/pip-build-env-6t_et_ky/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
        self.run_setup()
      File "/tmp/pip-build-env-6t_et_ky/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 497, in run_setup
        super().run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-6t_et_ky/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
        exec(code, locals())
      File "<string>", line 26, in <module>
      File "/tmp/pip-install-g05f_xe7/jpype1_306aae43c5094b6a987c28393e0cfd40/setupext/__init__.py", line 25, in <module>
        from . import pytester
      File "/tmp/pip-install-g05f_xe7/jpype1_306aae43c5094b6a987c28393e0cfd40/setupext/pytester.py", line 20, in <module>
        from setuptools.command.test import test as TestCommand
    ModuleNotFoundError: No module named 'setuptools.command.test'
```

**Comment by ilitygergo** [comment]
Solution can be found here in the meantime: https://github.com/pypa/setuptools/issues/4519#issuecomment-2254983472

**Comment by PrimWILL** [comment]
@ilitygergo Thx :) I hope this will be solved soon
