### ISSUE TITLE
ImportError: dlopen(/usr/local/bin/_jpype.so, 2): Symbol not found: _PyCObject_Type

### ISSUE THREAD

**Issue by sollymay** [jpype-project/jpype#389]
Hi Guys,

I am starting to migrate code from python 2.7 to python 3.7 and today, trying to use JPype, I got the following error. I am on MacOS Mojave 10.14.2 and installed Jpype through pip --> pip install jpype1

Not sure how to fix this one:

```
Traceback (most recent call last):
  File "pachifer.py", line 4, in <module>
    import jpype
  File "/usr/local/bin/jpype/__init__.py", line 17, in <module>
    from ._jpackage import *
  File "/usr/local/bin/jpype/_jpackage.py", line 18, in <module>
    import _jpype
ImportError: dlopen(/usr/local/bin/_jpype.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /usr/local/bin/_jpype.so
  Expected in: flat namespace
 in /usr/local/bin/_jpype.so
```

Thank you for your help!

**Comment by sollymay** [comment]
Fixed my own issue by uninstalling with pip2.7 and installing with pip3. 💃
