### ISSUE TITLE
JDK 12 causes NullPointerException when calling method via reflection

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#508]
This is a problem similar to s-u/rJava#175.  Apparently calling via reflection is using the same method that causes so much problems with forname and Database calls.  It is looking for the caller class that does not exist.

```
java.lang.NullPointerException
        at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Reflection.java:130)
        at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(AccessibleObject.java:673)
        at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:666)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:638)
        at java.base/java.lang.reflect.Method.invoke(Method.java:559)
```

It seems like it won't be fixed for Java 12.  Of course if we can understand how to work around this it would removed that entire limitation.

**Comment by Thrameos** [comment]
Looking at this problem with greater detail it is clear any method with the annotation "@CallerSensitive" will not work from within JPype as the class type for the caller will not be present.   It should be possible to check for this annotation for versions of the JDK will it.  When this annotation is found, the method can call a proxy method instead.  It may be difficult with series 0.7.

**Comment by Thrameos** [comment]
@marscher This issue is a bit more sever that I was hoping.  Because Java 12 won't be fixing this defect, we will have to deal with it as long as Java 12 is in use.  Calling via reflection must always be an option of our module as sometimes reflection is the most appropriate way to hit a specific overload or to access a private method.   Thus I don't see any other option than to address this.   (Even if I were to get the attention of the JDK developers, it would be a long time before the necessary hooks could appear as  it would certainly be a "big deal" to cut a new JNI version.)

The fundamental issue is that certain calls in Java consult the stackframe to get the origin of the call.  Any calls initiated from outside the JVM will have this issue as none of them have an originating stackframe thus the search fails resulting in NullPointerExceptions from all affected routines.  I searched the JNI documentation and the source code for the JVM and could find no solutions other than workarounds.  This is really not our issue as it is clear that the programmers of the JVM never thought through the implications of this particular calling structure or they would have given a "set initial stackframe" command for starting the JVM.  In Java 12 they accidentally introduced this path to "call via reflection", which is not optional for our module.  Grepping the Java source code, I now have full list of all of the affected calls.  It is certainly much larger than the Class forName and SQL DriverManager than I was previously aware.

In order to make a general workaround, we need some hooks in our internal library to call a method indirectly from within the JVM.  The good news is that the annotation we need is runtime retention so we can get it via reflection so I can fix this in general for all the calls.  The bad news is that it is a private internal notation, so I am going to need to access indirectly by name (somewhat of a performance hit).  Also since this is on an individual method rather then the whole dispatch, I am not going to be able to do the majority of the fix at Python level.  Thus most of this code is going to be in C++.   With regard to Java 12, I would need to control the scope on this bug fix.  I believe the faulty call is not marked with the annotation thus we are going to have to employ class customizers to fix the problem, and those fixes are going to need to be for one specific JVM version.  

I have placed no provisions at all regarding controlling the customizers for a specific version.  Customizers are installed in jpype prior to any jvm being started, and then applied with the class is created.  I can add a "version" keyword argument to target a specific version or a range of versions.  But all of this was outside plans for the 0.7 series.  Thus on the Python side it is just a matter of adding some decision logic to tell it to point patch the unmarked call.  But the rest will require adding more control hooks and a secondary callable path which is doable, but not easy in 0.7.  Much of the machinery that I would be patching is buried in 0.7 which is way I had started working on 0.8.  But JPype 0.8 is still too far from production for it to be a viable option currently.

This is also going to be a code coverage issue for testing, as hitting this version 12 specific code will require having a version that is busted unless I rig up something using mock to fake it on another JVM.  I believe I have found a way to cause the non-version specific problem to appear in our harness code so at least some of the paths can be exercised directly.   I am guessing that this will take at least a week of given the number of items that need to be touched (Python jpype module, C++ common, Java internal library, Java harness code, and Python test module).

**Comment by Thrameos** [comment]
5 hours spent thus far and I still can't replicate the problem.  They have locked down both the annotation "jdk.internal.reflect.Reflection" and "jdk.internal.reflect.CallerSensitive" so tight it is darn near impossible to make a simple test case.

Thus far I have figured out that I need to get this code to compile.

``` java
package jpype.bug;

import jdk.internal.reflect.CallerSensitive;
import jdk.internal.reflect.Reflection;

public class Caller
{
    @CallerSensitive
    public static Class callStatic() {
        return Reflection.getCallerClass();
    }

    @CallerSensitive
    public Class callMember() {
        return Reflection.getCallerClass();
    }

    @CallerSensitive
    public Class call(Object a, Object b) {
        return Reflection.getCallerClass();
    }
};
```

It can be compiled with the flags ``--add-exports java.base/jdk.internal.reflect=ALL-UNNAMED``.  Unfortunately, that doesn't allow me to run it.

I have tried every combination of startJVM I can think of and I can't seem to get the code to execute.

``` python
import jpype
jpype.startJVM("-Djdk.module.addexports=java.base/jdk.internal.reflect,ALL-UNNAMED", classpath="test/classes", convertStrings=False)
test1 = jpype.JClass('jpype.bug.Caller')()
print(test1.callStatic())
print(test1.callMember())
```

But it insists
```
$ python test2.py
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring system property options whose names match the '-Djdk.module.*'. names that are reserved for internal use.
Traceback (most recent call last):
  File "test2.py", line 4, in <module>
    print(test1.callStatic())
jpype._jclass.IllegalAccessError: class jpype.bug.Caller (in unnamed module @0x33833882) cannot access class jdk.internal.reflect.Reflection (in module java.base) because module java.base does not export jdk.internal.reflect to unnamed module @0x33833882
```

Surely they have planned some sort of API to access this.  But every API that touches the module is also CallerSensitive and thus also barred because I can't set the initial stackframe.
