### ISSUE TITLE
Install failed due to AttributeError

### ISSUE THREAD

**Issue by MarkHe1222** [jpype-project/jpype#651]
```
$ python -m pip install -t ./ JPype1 --upgrade
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting JPype1
  Using cached JPype1-0.7.2.tar.gz (537 kB)
Installing collected packages: JPype1
    Running setup.py install for JPype1: started
    Running setup.py install for JPype1: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\hem4\\appdata\\local\\temp\\pip-install-akkunw\\JPype1\\setup.py'"'"'; __file__='"'"'c:\\users\\hem4\\appdata\\local\\temp\\pip-install-akkunw\\JPype1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\hem4\appdata\local\temp\pip-record-7sk3ll\install-record.txt' --single-version-externally-managed --home 'c:\users\hem4\appdata\local\temp\pip-target-kzrbhw' --compile --install-headers 'c:\users\hem4\appdata\local\temp\pip-target-kzrbhw\include\python\JPype1'
         cwd: c:\users\hem4\appdata\local\temp\pip-install-akkunw\JPype1\
    Complete output (95 lines):
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\jpype
    copying jpype\beans.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\imports.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\nio.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\pickle.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\reflect.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\types.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_classpath.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_core.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_cygwin.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_darwin.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_gui.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jarray.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jclass.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jcollection.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jcomparable.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jcustomizer.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jexception.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jinit.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jio.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jmethod.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jobject.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jpackage.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jproxy.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jstring.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jtypes.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_jvmfinder.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_linux.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_pykeywords.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\_windows.py -> build\lib.win-amd64-2.7\jpype
    copying jpype\__init__.py -> build\lib.win-amd64-2.7\jpype
    running build_ext
    running build_java
    Using Jar cache
    creating build\lib
    creating build\lib\org
    creating build\lib\org\jpype
    creating build\lib\org\jpype\classloader
    copying native\jars\org\jpype\classloader\JPypeClassLoader.class -> build\lib\org\jpype\classloader
    copying native\jars\org.jpype.jar -> build\lib
    running build_thunk
    Building thunks
      including thunk build\lib\org\jpype\classloader\JPypeClassLoader.class
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\hem4\appdata\local\temp\pip-install-akkunw\JPype1\setup.py", line 52, in <module>
        use_scm_version = True,
      File "C:\Python27\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "C:\Python27\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "setupext\build_ext.py", line 73, in build_extensions
        self.run_command("build_thunk")
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "setupext\build_thunk.py", line 153, in run
        namespace="JPThunk")
      File "setupext\build_thunk.py", line 103, in createThunks
        outputClass(filename, name, fimpl)
      File "setupext\build_thunk.py", line 53, in outputClass
        output(fout, l)
      File "setupext\build_thunk.py", line 36, in output
        buffer.frombytes(l)
    AttributeError: 'array.array' object has no attribute 'frombytes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\hem4\\appdata\\local\\temp\\pip-install-akkunw\\JPype1\\setup.py'"'"'; __file__='"'"'c:\\users\\hem4\\appdata\\local\\temp\\pip-install-akkunw\\JPype1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\hem4\appdata\local\temp\pip-record-7sk3ll\install-record.txt' --single-version-externally-managed --home 'c:\users\hem4\appdata\local\temp\pip-target-kzrbhw' --compile --install-headers 'c:\users\hem4\appdata\local\temp\pip-target-kzrbhw\include\python\JPype1' Check the logs for full command output.
```

**Comment by Thrameos** [comment]
Uh, I believe that most relevant line was the second from the top
```
Python 2.7 reached the end of its life on January 1st, 2020
```

JPype1 dropped support for Python 2.7 on January 1st, 2020.   Versions released prior to that date will continue to function, but all versions after that date had Python 2.7 support removed.  Should you compile an further past that point you would find that JPype does a great many things that are incompatible the Python 2.7 object model.   It is simply not possible to both advance compatibility with the Python 3 branch and maintain compliance to an object model from July 3, 2010.  It took great lengths to support both for the past 3 years at the cost of efficiency and capabilities.  Thus we cannot support Python 2.7 any further.  I recommend pinning your installer to a prior version.

Sorry.
