### ISSUE TITLE
Imports does not properly report java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#697]
Example

```
 File "TypeManager.java", line 166, in org.jpype.manager.TypeManager.findClassByName
  File "Class.java", line 315, in java.lang.Class.forName
  File "Class.java", line -2, in java.lang.Class.forName0
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test2.py", line 6, in <module>
    db= jpype.JClass('org.my.Database')

```

Actual cause was 

```
Caused by: java.nio.file.NoSuchFileException: ./app.properties
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:155)
        at org.my.getProperties(ApplicationProperties.java:53)
        ... 4 more
```

**Comment by marscher** [comment]
which versions are affected of this?

**Comment by Thrameos** [comment]
I only tested the latest version.   It may have reported properly in 0.7.0 which used the old type manager.
