### ISSUE TITLE
Setup for Python 2.7 fails

### ISSUE THREAD

**Issue by baztian** [jpype-project/jpype#754]
I can't get JPype 0.7.2+ installed in Python 2.7. Is Python 2.7 still supported?

    Building thunks
      including thunk build/lib/org/jpype/classloader/JPypeClassLoader.class
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ayWnsX/JPype1/setup.py", line 52, in <module>
        use_scm_version = True,
      File "/home/me/Sources/jaydebeapi/.tox/py27-driver-hsqldb-newjpype/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/me/Sources/jaydebeapi/.tox/py27-driver-hsqldb-newjpype/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/me/Sources/jaydebeapi/.tox/py27-driver-hsqldb-newjpype/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "setupext/build_ext.py", line 73, in build_extensions
        self.run_command("build_thunk")
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setupext/build_thunk.py", line 153, in run
        namespace="JPThunk")
      File "setupext/build_thunk.py", line 103, in createThunks
        outputClass(filename, name, fimpl)
      File "setupext/build_thunk.py", line 53, in outputClass
        output(fout, l)
      File "setupext/build_thunk.py", line 36, in output
        buffer.frombytes(l)
    AttributeError: 'array.array' object has no attribute 'frombytes'

https://github.com/jpype-project/jpype/blob/57fd1afb00b40a7addb2e068b5536724a6c9f509/setupext/build_thunk.py#L35

According to https://stackoverflow.com/a/52330049/1960601 for Python 2 the fromstring method can be used...

**Comment by Thrameos** [comment]
Sorry.  After 0.7.1 no further support for Python 2.7 was possible.   The object model of JPype is very tied to the internals of Python and it was literally a 10-100 times slower to try to support the Python 2 model thus we dropped support for 2.7 at end of service life.   Once 2.7 reached end of service life we could finally move all of the support mechanisms to the Python 3 object model and remove all exposed private variables.
