### ISSUE TITLE
Struggling to use a listener from Java in python

### ISSUE THREAD

**Issue by Technisha** [jpype-project/jpype#926]
Heya! I saw Jpype and i was testing it out today, and for my first test i am trying to use Javacord! Everything works except for using the listener, any idea on how i can use a Java listener in Python? I tried using it as a decorator but i got an error so i'm assuming that wouldn't work, any help is appreciated, thanks!

**Comment by Thrameos** [comment]
If you can post an example of what you are trying to do I can likely give you some tips.

**Comment by Technisha** [comment]
Heya! Thanks for responding, here's my code:
```python
from jpype import startJVM, JImplements, JOverride
import jpype.imports
from jpype.types import *

startJVM(classpath=['jars/*'])

from org.javacord.api import DiscordApi
from org.javacord.api import DiscordApiBuilder
from org.javacord.api.listener.message import MessageCreateListener as JMessageCreateListener

vapi = DiscordApiBuilder().setToken(JString("My Bot Token")).login().join()

@JImplements(JMessageCreateListener)
class MessageCreateListener(object):
    def __init__(self):
        pass

    @JOverride
    def onMessageCreate(self, event):
        if event.getMessageContent().lower() == "!ping":
            event.getChannel().sendMessage(JString("Pong!"))

vapi.addListener(MessageCreateListener())
```
And here's the error i'm getting:
```2021-01-20 09:56:46.818+0000 INFO org.javacord.core.util.logging.ExceptionLoggerDelegateImpl No Log4j2 compatible logger was found. Using default Javacord implementation!
2021-01-20 09:57:02.642+0000 ERROR org.javacord.core.util.event.EventDispatcherBase Unhandled exception in a listener thread for 3Lovers4Ever! {shard=0} 
 org.jpype.PyExceptionProxy
        at org.jpype.JPypeContext.createException(Unknown Source)
        at org.jpype.proxy.JPypeProxy.hostInvoke(Native Method)
        at org.jpype.proxy.JPypeProxy.invoke(Unknown Source)
        at com.sun.proxy.$Proxy6.onMessageCreate(Unknown Source)
        at org.javacord.core.util.event.EventDispatcher.lambda$dispatchMessageCreateEvent$102(EventDispatcher.java:3636)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$dispatchEvent$10(EventDispatcherBase.java:197)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$17(EventDispatcherBase.java:265)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-20 09:57:03.545+0000 ERROR org.javacord.core.util.event.EventDispatcherBase Unhandled exception in a listener thread for 3Lovers4Ever! {shard=0} 
 org.jpype.PyExceptionProxy
        at org.jpype.JPypeContext.createException(Unknown Source)
        at org.jpype.proxy.JPypeProxy.hostInvoke(Native Method)
        at org.jpype.proxy.JPypeProxy.invoke(Unknown Source)
        at com.sun.proxy.$Proxy6.onMessageCreate(Unknown Source)
        at org.javacord.core.util.event.EventDispatcher.lambda$dispatchMessageCreateEvent$102(EventDispatcher.java:3636)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$dispatchEvent$10(EventDispatcherBase.java:197)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$17(EventDispatcherBase.java:265)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by Thrameos** [comment]
The error message indicates that a unhandled exception is leaking into the proxy.   I would recommend catching it to see what is going on.

```
    @JOverride
    def onMessageCreate(self, event):
        try:
          if event.getMessageContent().lower() == "!ping":
              event.getChannel().sendMessage(JString("Pong!"))
         except Exception as ex:
             print(ex)
             raise ex
```

**Comment by Technisha** [comment]
Ah! That fixed the issue thanks! It seems like the problem we were having before was that we were trying to use `.lower()` on a Java object, thank you again!

**Comment by Thrameos** [comment]
No problem.  Though this is the place where I look for feedback to improve things.  I few quick questions help in resolving this sort of question in the future.

1) Did you look through the JPype documentation regarding Proxies?  (It is fine if you didn't, I just need to know where you looked before putting in an issue so I can judge the effort that should be placed on documentation.) 
2) Was it clear from the documentation that Python exceptions would be transferred into Java? 
3) Looking at it now, is the name of the exception (org.jpype.PyExceptionProxy) clear that this was Python generated exception?
4) Is there anything in the way of improved documentation that would have made it easier to have resolved your issue?

Your case was a bit unusual as the call did not originate from Python. Normally if Python had been in the call stack would have been unwrapped back into a Python exception.   But in your case a Java thread launched the proxy and thus its handlers got an exception that was wrapped from Python.

I do see one improvement that can be made.   The 3rd party code should have gotten a message with the contents of the Python exception so that you don't have to add the try block to get the attribute error "lower not found".  Though this may have be a problem in the 3rd party logger.  I haven't tried getting the message from a PyExceptionProxy to see how useful it is.

**Comment by Technisha** [comment]
For the first question, yeah i skimmed through the docs multiple times (though i probably wasn't paying full attention), for the second question, not really 😅, i thought that all Java exceptions would be converted to a python exception somehow, for the 3rd, yeah it was clear that python caused this issue, but it didn't really have any information that could help me figure out what the issue actually was. And i think the docs weren't the issue, but a note that some python methods might not work on Java objects (without some formatting/processing) would be pretty nice to remind anyone in the future that the error could be an issue from python

**Comment by Thrameos** [comment]
Thank you for your comments.  And good luck with your project!
