### ISSUE TITLE
Version 1.2.1 failed to execute the test

### ISSUE THREAD

**Issue by simon28li** [jpype-project/jpype#947]
The test failed after installing version 1.2.1, and the log is as follows:
```
Skip building Java testbench
====================================================================================== test session starts =======================================================================================
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.10.0, pluggy-1.0.0.dev0 -- /home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/bin/python
cachedir: .pytest_cache
rootdir: /tmp/root/spack-stage/spack-stage-py-jpype1-1.2.1-jo3i2vsoyeevfwvdtnbt2elngpzzpjb5/spack-src, configfile: setup.cfg, testpaths: test, jpype/_pyinstaller
collected 0 items / 1 error

============================================================================================= ERRORS =============================================================================================
_________________________________________________________________________________ ERROR collecting test session __________________________________________________________________________________
.eggs/pluggy-1.0.0.dev0-py3.8.egg/pluggy/manager.py:128: in register
    hook._maybe_apply_history(hookimpl)
.eggs/pluggy-1.0.0.dev0-py3.8.egg/pluggy/hooks.py:328: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
.eggs/pluggy-1.0.0.dev0-py3.8.egg/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.eggs/pluggy-1.0.0.dev0-py3.8.egg/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: _multicall(
test/sql/conftest.py:7: in pytest_addoption
    parser.addoption('--classpath', action="store", default=None,
.eggs/pytest-6.2.2-py3.8.egg/_pytest/config/argparsing.py:96: in addoption
    self._anonymous.addoption(*opts, **attrs)
.eggs/pytest-6.2.2-py3.8.egg/_pytest/config/argparsing.py:355: in addoption
    raise ValueError("option names %s already added" % conflict)
E   ValueError: option names {'--classpath'} already added
==================================================================================== short test summary info =====================================================================================
ERROR  - ValueError: option names {'--classpath'} already added
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================================== 1 error in 0.52s ========================================================================================
```
my system is CentOS 8, kernel is 4.18.0-193.el8.aarch64
Can you give me some help?

**Comment by simon28li** [comment]
@Thrameos ,Can you give me some help? Thank you very much.

**Comment by Thrameos** [comment]
It isn't clear what is failing here.  Is this the jpype test bench or some software using jpype?  The error message is classpath was specified twice which without knowing the line that was executed is hard to tell.

**Comment by rapgro** [comment]
pytest works with one conftest.py only, there's a conflict when run from top level folder as conftest.py found in both jpypetest and sql subfolders.
After removed sql/conftest.py I get:
```
ERROR collecting jpype/_pyinstaller/test_jpype_pyinstaller.py _________
ImportError while importing test module '/builddir/build/BUILD/jpype-1.2.1/jpype/_pyinstaller/test_jpype_pyinstaller.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
jpype/_pyinstaller/test_jpype_pyinstaller.py:6: in <module>
    import PyInstaller.__main__
E   ModuleNotFoundError: No module named 'PyInstaller'
```

**Comment by simon28li** [comment]
> It isn't clear what is failing here. Is this the jpype test bench or some software using jpype? The error message is classpath was specified twice which without knowing the line that was executed is hard to tell.
hi,I just download the source package and execute python setup.py test after compilation and installation.

**Comment by simon28li** [comment]
> It isn't clear what is failing here. Is this the jpype test bench or some software using jpype? The error message is classpath was specified twice which without knowing the line that was executed is hard to tell.

hi,I just download the source package and execute python setup.py test after compilation and installation.

**Comment by simon28li** [comment]
> pytest works with one conftest.py only, there's a conflict when run from top level folder as conftest.py found in both jpypetest and sql subfolders.
> After removed sql/conftest.py I get:
> 
> ```
> ERROR collecting jpype/_pyinstaller/test_jpype_pyinstaller.py _________
> ImportError while importing test module '/builddir/build/BUILD/jpype-1.2.1/jpype/_pyinstaller/test_jpype_pyinstaller.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /usr/lib64/python3.9/importlib/__init__.py:127: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> jpype/_pyinstaller/test_jpype_pyinstaller.py:6: in <module>
>     import PyInstaller.__main__
> E   ModuleNotFoundError: No module named 'PyInstaller'
> ```

You're right. I made the same error as you said. I was able to run the test case after I installed pyinstaller, but I reported a lot of failures.
```
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testNumeric ERROR                                                                                                                         [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testReal FAILED                                                                                                                           [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testReal ERROR                                                                                                                            [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testSmallInt FAILED                                                                                                                       [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testSmallInt ERROR                                                                                                                        [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testTime FAILED                                                                                                                           [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testTime ERROR                                                                                                                            [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testTimestamp FAILED                                                                                                                      [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testTimestamp ERROR                                                                                                                       [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testTinyInt FAILED                                                                                                                        [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testTinyInt ERROR                                                                                                                         [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testVarBinary FAILED                                                                                                                      [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testVarBinary ERROR                                                                                                                       [ 94%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testVarChar FAILED                                                                                                                        [ 95%]
test/jpypetest/test_sql_sqlite.py::TypeTestCase::testVarChar ERROR                                                                                                                         [ 95%]
test/jpypetest/test_sql_sqlite.py::OtherTestCase::testJSON FAILED                                                                                                                          [ 95%]
test/jpypetest/test_sql_sqlite.py::OtherTestCase::testJSON ERROR                                                                                                                           [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_callproc SKIPPED                                                                                                                [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_close FAILED                                                                                                                    [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_close ERROR                                                                                                                     [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_execute FAILED                                                                                                                  [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_execute ERROR                                                                                                                   [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_executemany FAILED                                                                                                              [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_executemany ERROR                                                                                                               [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_fetchall FAILED                                                                                                                 [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_fetchall ERROR                                                                                                                  [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_fetchmany FAILED                                                                                                                [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_fetchmany ERROR                                                                                                                 [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_fetchone FAILED                                                                                                                 [ 95%]
test/jpypetest/test_sql_sqlite.py::ThreadingTestCase::test_fetchone ERROR                                                                                                                  [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testBadKeyword ERROR                                                                                                                         [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testClasspathArgDef ERROR                                                                                                                    [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testClasspathArgKeyword ERROR                                                                                                                [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testClasspathArgList ERROR                                                                                                                   [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testClasspathArgListEmpty ERROR                                                                                                              [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testClasspathBadType ERROR                                                                                                                   [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testClasspathTwice ERROR                                                                                                                     [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testInvalidArgsFalse ERROR                                                                                                                   [ 95%]
test/jpypetest/test_startup.py::StartJVMCase::testInvalidArgsTrue ERROR                                                                                                                    [ 96%]
test/jpypetest/test_startup.py::StartJVMCase::testJVMPathKeyword ERROR                                                                                                                     [ 96%]
test/jpypetest/test_startup.py::StartJVMCase::testPathArg Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-u4wpsnkl'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-9fd307pg'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-2pxn5kyh'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-z3ibcp1l'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-0rhxvurn'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-p7vkphcx'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-rk9e445b'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-lz8id1f7'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-nth_hndr'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-chwmzqh6'
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.7-a5lviv725d2uukam67umjs6kkihuqbvm/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/mp-q7k9oeny'
```

**Comment by rapgro** [comment]
@simon28li As you seem interested in CentOS 8, are you interested in co-maintaining this as downstream package? I'm happy to welcome co-maintainer for EPEL branch.

For tests failure, maybe try to skip test_sql_sqlite and test_startup. Could we make the output be more verbose? What about the other tests, successful?

**Comment by Thrameos** [comment]
Normally I run the tests with ``python -m pytest test/jpypetest``.
